apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-api-deployment
  namespace: king-akademija-2023
spec:
  selector:
    matchLabels:
      app: meetup-api
  replicas: 1
  template:
    metadata:
      labels:
        app: meetup-api
    spec:
      containers:
        - name: meetup-api-container
          image: >-
            default-route-openshift-image-registry.apps.ocp.dev.king-ict.corp/king-akademija-2023/meetup-image-stream:1
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8080
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: meetup-api-service
  namespace: king-akademija-2023
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  selector:
    app: meetup-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

